#!/bin/bash

PERSON1=Subbu
PERSON2=gayi

echo "$PERSON1:: Hi $PERSON2, how r u"
echo "$PERSON2:: Hlo $PERSON1, Iam fine"
echo "$PERSON1:: what are you doing?"
echo "$PERSON2:: Thinking about only."
echo "$PERSON1:: oh really,ok good"