#!/bin/bash

echo "all variables passed to the script: $@"
echo "number of variables passed to the script: $#"
echo "script name: $0" 
echo "present working directory: $PWD"
echo "which user is running the script: $USER"
echo "home directory of the user who is running the script: $HOME"
echo "pid of the current script: $$"
sleep 10& 
echo "pid of the last command running in background: $!"
echo "exit status of last command: $?"