#!/bin/bash 
NUMBER=$1 

#-gt -->gretaer than 
#-lt---> less than
#-eq---> equal to 
#-ne---> not equal 

if [ $NUMBER -lt 10 ]
then 
   echo "given number is less than 10"
else 
   echo "given number is greter than 10"
fi       