#!/bin/bash

echo " hi iam subbu i love to read devops engineer but im faacing lot of problems in this course we need to resolve the problems in this"
echo "hlo supriya i love u im waiting for ur message to develope the code into the staging market to went outside of the builders to it"