#!/bin/bash 
USERID=$(date) 

R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

LOGS_FOLDER="var/log/shellscript-logs"
SCRIPT_NAME=$( echo $0 | cut -d "." -f1 )
LOG_FILE="$LOGS_FOLDER/SCRIPT_NAME.log"

mkdir -p $LOGS_FOLDER 
echo "script execution statrted at: $(date)"

if [ $USERID -ne 0 ]
then 
   echo -e "$R ERROR:: please run this script with root access $N"
   exit 1 
else 
   echo "you are running with root access" 
fi 

# valiadte function takses input as exit status what command they tried to install 
VALIDATE() {
  if [ $1 -eq 0 ]
  then 
     echo -e "installing $2 is... $G SUCCESS $N" 
  else 
     echo -e "installing $2 is... $R FAILURE $N" 
     exit 1 
  fi    
}

dnf list installed mysql -y 
if [ $? -ne 0 ]
then
   echo -e "mysql is not installed... going to install"
   dnf install mysql -y 
   VALIDATE $? "MYSQL" 
else 
   echo -e "nothing to do mysql... $Y already installed $N" 
fi        

dnf list installed python3 -y 
if [ $? -ne 0 ]
then
   echo -e "python3 is not installed... going to install"
   dnf install python3 -y 
   VALIDATE $? "python3" 
else 
   echo -e "nothing to do python3... $Y already installed $N" 
fi        

dnf list installed nginx -y 
if [ $? -ne 0 ]
then
   echo -e "nginx is not installed... going to install"
   dnf install nginx -y 
   VALIDATE $? "nginx" 
else 
   echo -e "nothing to do nginx... $Y already installed $N" 
fi        
