#!/bin/bash 
USERID=$(id -u) 

R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

LOGS_FOLDER="/var/log/shellscript-logs"
SCRIPT_NAME=$( echo $0 | cut -d "." -f1 )
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"
PACKAGES=("mysql" "nginx" "httpd" "python3")

mkdir -p $LOGS_FOLDER 
echo -e "script execution started at: $(date)" | tee -a $LOG_FILE

if [ $USERID -ne 0 ]
then 
   echo -e "$R ERROR:: please run the script with root access $N" | tee -a $LOG_FILE 
   exit 1    
else 
   echo  "you are running with root access" | tee -a $LOG_FILE 
fi 

# validate function takes input as exit status what comand tried to install 
VALIDATE() {
  if [ $1 -eq 0 ]
  then 
     echo -e "installing $2 is... $G SUCCESS $R" | tee -a $LOG_FILE 
  else 
     echo -e "installng $2 is... $R FAILURE $N" | tee -a $LOG_FILE 
     exit 1   
  fi    
}

for package in ${PACKAGES[0]}
do
dnf list installed $package -y &>>$LOG_FILE
if [ $? -ne 0 ]
then 
   echo  "$package is not insttalled... going to install" | tee -a $LOG_FILE 
   dnf install $package -y &>>$LOG_FILE
   VALIDATE $? "$PACKAGE" 
else 
   echo -e "nothing to do $package... $Y already installed $N" | tee -a $LOG_FILE 
fi       
done 


