#!/bin/bash

USERID=$(id -u)
SOURCE_DIR=$1
DEST_DIR=$2
DAYS=$(3:-14)

R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

LOGS_FOLDER="/var/log/shellscript-logs"
SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
LOG_FILE="$LOGS_FOLDER/backup.log"


mkdir -p $LOGS_FOLDER
echo "Script started execution at : $(date)" | tee -a $LOG_FILE
check_root(){
if [ $USERID -ne 0 ]
then 
   echo -e "$R ERROR:: please run this script with root access $N" | tee -a $LOG_FILE
    exit 1 # give other than 0 upto 127
else
   echo "you are running with root access" | tee -a $LOG_FILE
fi 
}

#validate function takes input as exit status what command they tried to install

VALIDATE(){
   if [ $1 -eq 0 ]
   then 
      echo -e "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE 
   else
      echo -e "Installing $2 is ... $R FAILURE $N" | tee -a $LOG_FILE
      exit 1
   fi      
}
USAGE(){
   echo -e "$R USAGE:: $N 20-backup-1 <source-directory> <destination-directory> <optional(days)>" | tee -a $LOG_FILE
   exit 
}

if [ ! -d $SOURCE_DIR ]
then 
  echo -e "$R source directory $SOURCE_DIR does not exist please check $N" | tee -a $LOG_FILE
  exit 1
fi 

if [ ! -d $DEST_DIR ]
then 
  echo -e "$R destnation directory $DEST_DIR does not exixt please check $N" | tee -a $LOG_FILE
  exit 1 
fi 

FILES=$(find $SOURCE_DIR -name "*.log" -mtime +14) | tee -a $LOG_FILE
if [ ! -z "$FILES" ] 
then 
  echo "files to zip are: $FILES" | tee -a $LOG_FILE
  TIMESTAMP=$(date +%F -%m-%h-%s) | tee -a $LOG_FILE
  ZIP_FILES=$DEST_DIR/app-logs-$TIMESTAMP.zip | tee -a $LOG_FILE
  find $SOURCE_DIR -name "*.log" -mtime +14 | zip -@ "$ZIP_FILES" | tee -a $LOG_FILE
if [ -f "ZIP_FILES" ] 
then 
   echo "successfully created a zip file" | tee -a $LOG_FILE
   while IFS= read -r filepath 
   do 
     echo "Deleting file: $filepath"
     rm -rf $filepath 
   done < $FILES 
  echo -e "log files older than 14days found from source directory removed... $G SUCCESS $N" | tee -a $LOG_FILE
else 
   echo -e "zip file creation... $R FAILURE $N" | tee -a $LOG_FILE 
   exit 1
fi 
else 
  echo -e "no log files found older than 14days... $Y SKIPPING $N" | tee -a $LOG_FILE
fi 
END_TIME=$(date +%s)
TOTAL_TIME=$(( $END_TIME - $START_TIME ))
echo -e "script execution completed successfully, $Y time taken: $TOTAL_TIME seconds $N" | tee -a $LOG_FILE 

