#!/bin/bash

USERID=$(id -u)
SOURCE_DIR=$1
DEST_DIR=$2
DAYS=${3:-14}

LOGS_FOLDER="/var/log/shellscript-logs"
SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
LOG_FILE="$LOGS_FOLDER/backup.log"
R="\e[31m"
G="\e[32"
Y="\e[33m"
N="\e[0m"

mkdir -p $LOGS_FOLDER
echo "Script started execution at: $(date)" | tee -a $LOG_FILE

if [ $USERID -ne 0 ]
then 
   echo -e "$R ERROR:: please run the script with root access $N" | tee -a $LOG_FILE
   exit 1
else
   echo "you are running with root access" | tee -a $LOG_FILE
fi

# validate function takes as a input as exit status what command that they tried to install
VALIDATE(){
    if [ $1 -eq 0 ]
    then 
       echo -e "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
    else 
       echo -e "Installing $2 is ... $R FAILURE $N" | tee -a $LOG_FILE
       exit 1 
    fi   
}

usage(){
    echo "$R USAGE:: $N sh 20-backup-1 <source-directory> <destination-directory> <days(optional)>"
}

if [ $# -lt 0 ]
then 
    usage
fi

if [ ! -d $SOURCE_DIR ]
then
    echo -e "$R source directory $SOURCE_DIR does not exist please check $N"
    exit 1
fi

if [ $# -lt 0 ]
then
    echo -e  "$R destination directory $DEST_DIR does not exist please check $N"
    exit 1
fi     
