#!/bin/bash
USERID=$(id -u)
SOURCE_DIR=$1
DEST_DIR=$2
DAYS=$(3:-14)

LOGS_FOLDER="/var/log/shellscript-logs"
SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
LOG_FILE="$LOGS_FOLDR/$SCRIPT_NAME.log"

R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

mkdir -p $LOGS_FOLDER

if [ $USERID -ne 0 ]
then 
   echo -e "$R ERROR:: please run this script with root access $N" | tee -a $LOG_FILE
   exit 1 
else
    echo "you are running with root access" | tee -a $LOG_FILE
fi

#validate function takes input as exit status what command that they trird to install

VALIDATE(){
    if [ $1 -eq o ]
    then 
        echo -e "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
    else 
        echo -e "Installing $2 is ... $R FAILURE $N" | tee -a $LOG_FILE  
    fi      
}

echo "script started execution successfully at: $(date)"  | tee -a $LOG_FILE

usage(){
    echo -e "$R USAGE:: $N backup <sourcr-dir> <destination-dir> <days(optional)>"
    exit 1 
}

if [ $# -lt 2 ]
then 
   usage
fi


