#!/bin/bash
USERID=$(id -u)
SOURCE_DIR=$1
DEST_DIR=$2
DAYS=${3:-14}

    R="\e[31m"
    G="\e[32m"
    Y="\e[33m"
    N="\e[0m"

    LOGS_FOLDER="/var/log/shellscript-logs"
    SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
    LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"
    

    mkdir -p $LOGS_FOLDER
    echo "script started execution at: $(date)" | tee -a $LOG_FILE

    if [ $USERID -ne 0 ]
    then
       echo -e "$R ERROR:: please run this script with root access $N" | tee -a $LOG_FILE
       exit 1
    else 
        echo  "you are running with roo access" | tee -a $LOG_FILE
    fi 

    # Validate function takes input as exit status what command tried to install
    VALIDATE(){
        if [ $1 -eq 0 ]
        then
            echo -e "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE 
        else 
             echo -e "Installing $2 is ... $R FAILURE $N" | tee -a $LOG_FILE 
        fi         
    }   

    usage(){
        echo -e  "$R USAGE:: $N backup <source-directory> <destination-directory> <days(optional)>"
        exit 1
    }

    if [ $# -lt 2 ]
    then 
        usage
    fi

