#!/bin/bash

echo -e "\e[31m hello world"
echo  -e "\e[31m hello world"
echo -e "\e[33m hello world"
echo -e "\e[34m hello wolrd"
echo -e "\e[35m hello world"
echo -e "\e[36m hello world"
echo -e "\e[37 hello world"