#!/bin/bash

echo "all variables passed to the script: $@"
echo "number of variables:$#"
echo "script name:$0"
echo "present working directory:$PWD"
echo "home directory of the user who is running the script:$HOME"
echo "which user is running the script:$USER"
echo "PID of the script:$$"
echo "pid of the last command irunning background:$!"
echo "exit status of previous command:$?"