#!/bin/bash

echo "all variables passed to script: $@"
echo " number of variables passed: $#"
echo " script name: $0"
echo "present working directory: $PWD"
echo "home directory of the user in running script: $HOME"
echo "whivch user is running the script: $USER"
echo "pid of the command script: $$"
sleep 10 &

echo "pid of the last command runnig in background: $!"
echo " exit status of previous command: $?"