#!/bin/bash
SOURCE_DIR="/home/ec2-user/app-logs"
FILES_TO_DELETE=$(find $SOURCE_DIR -name -mtime +14)
    while IFS= read -r filepath
    do
       rm -rf $filepath
    done <<< $FILES_TO_DELETE  

    USERID=$(id -u)
    R="\e[31m"
    G="\e[32m"
    Y="\e[33m"
    N="\e[0m"

    LOGS_FOLDER="/var/log/shellscript-logs"
    SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
    LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"
    SOURCE_DIR="/home/ec2-user/app-logs"

    mkdir -p $LOGS_FOLDER
    echo "script started execution at: $(date)" | tee -a $LOG_FILE

    if [ $USERID -ne 0 ]
    then
       echo -e "$R ERROR:: please run this script with root access $N" | tee -a $LOG_FILE
       exit 1
    else 
        echo  "you are running with roo access" | tee -a $LOG_FILE
    fi 

    # Validate function takes input as exit status what command tried to install
    VALIDATE(){
        if [ $1 -eq 0 ]
        then
            echo -e "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE 
        else 
             echo -e "Installing $2 is ... $R FAILURE $N" | tee -a $LOG_FILE 
        fi         
    }   


FILES_TO_DELETE=$(find $SOURCE_DIR -name -mtime +14) | tee -a $LOG_FILE
while IFS= read -r filepath
do 
  echo "Deleting filepath: $filepath" | tee -a $LOG_FILE

  rm -rf $filepath
done <<< $FILES_TO_DELETE| tee -a $LOG_FILE

echo "script execution completed successfully" | tee -a $LOG_FILE
