#!/bin/bash
SOURCE_DIR="/home/ec2-user/app-logs"
FILES_TO_DELETE=$(find $SOURCE_DIR -name "*.log" -mtime +14)

while IFS= read -r filepath
do 
  echo $filepath

done <<<<<<< $FILES_TO_DELETE

USERID=$(id -u)
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

LOGS_FOLDER="/var/log/shellscript-logs"
SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"
SOURCE_DIR="/home/ec2-user/app-logs"

mkdir -p $LOGS_FOLDER

if [ $USERID -ne 0 ]
then 
   echo -e "$R ERROR:: please run this script with root access $N" | tee -a $LOG_FILE
   exit 1 
else
    echo "you are running with root access" | tee -a $LOG_FILE
fi

#validate function takes input as exit status what command that they trird to install

VALIDATE(){
    if [ $1 -eq o ]
    then 
        echo -e "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
    else 
        echo -e "Installing $2 is ... $R FAILURE $N" | tee -a $LOG_FILE    
}

echo "script started execution successfully at: $(date)"  | tee -a $LOG_FILE

FILES_TO_DELETE=$(find $SOURCE_DIR -name -mtime +14)
while IFS= read -r filepath
do 
  echo "Deleting file : $filepath" | tee -a $LOG_FILE
  rm -rf $filepath
done <<<<<<< $FILES_TO_DELETE

echo "script execution successfully"

