#!/bin/bash
USERID=$(id -u)
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

LOGS_FOLDER="/var/log/shellscript-logs"
SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
LOG_FILE=$LOGS_FOLDER/$SCRIPT_NAME

mkdir -p $LOGS_FOLDER
echo "script started executing at: $(date)" &>>$LOG_FILE

if [ $USERID -ne 0 ]
then
    echo -e "$R ERROR:: please run this script with root access $N" &>>$LOG_FILE
    exit 1
else 
    echo "you are running with root access" &>>$LOG_FILE
    
    
fi 

# validate function takes input as exit status what command they tried to install

VALIDATE(){
    if [ $1 -eq 0 ]
    then
        echo -e "installing $2 is...$G SUCCESS $N" &>>$LOG_FILE
    else
        echo "installing $2 is... $R FAILURE $N" &>>$LOG_FILE
    fi        
}

 
 dnf list installed mysql &>>$LOG_FILE
    if [ $? -ne 0 ]
    then   
    echo "mysql is not installed...going to install" &>>$LOG_FILE
    dnf install mysql -y &>>$LOG_FILE
    VALIDATE $? "MYSQL"
else 
    echo -e "nothing do mysql... $Y alraedy installed $N" &>>$LOG_FILE
fi        

dnf list installed python3 &>>$LOG_FILE
    if [ $? -ne 0 ]
    then   
    echo "python is not installed...going to install" &>>$LOG_FILE
    dnf install python3 -y &>>$LOG_FILE
    VALIDATE $? "PYTHON3"
else 
    echo -e "nothing to do python3... $Y already installed $N" &>>$LOG_FILE
fi        

dnf list installed nginx &>>$LOG_FILE
    if [ $? -ne 0 ]
    then   
    echo "nginx is not installed...going to install" &>>$LOG_FILE
    dnf install nginx-y &>>$LOG_FILE
    VALIDATE $? "NGINX"
else 
    echo -e "nothing to do nginx... $Y already installed $N" &>>$LOG_FILE
fi        


    