#!/bin/bash

USERID=$(id -u)
R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"
LOGS_FOLDER="/var/log/shrllsript-logs"
SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"

mkdir $LOGS_FOLDER
echo -e "Script started executed at: $(date)" &>>LOG_FILE
if [ $USERID -ne 0 ]
then 
   echo -e "$R ERROR:: please run the script with root access $N" &>>LOG_FILE
   exit 1
else
   echo "you are running root acces" &>>LOG_FILE
fi

# validate function takes input as exit status what command they tried to install
VALIDATE(){
    if [ $1 -eq 0 ]
    then
        echo "Installing $2 is ... $G SUCCESS $N" &>>LOG_FILE
    else
        echo "Installing $2 is ... $R FAILURE $N" &>>LOG_FILE
        exit 1
    fi         
}

dnf list installed mysql
if [ $? -ne 0 ]
then
   echo "mysql is not installed ... going to install" &>>LOG_FILE
   dnf install mysql -y &>>LOG_FILE
   VALIDATE $? "MYSQL"
else
    echo -e "mysql is already installed ... $Y nothing to do $N" &>>LOG_FILE
fi 

dnf list installed nginx &>>LOG_FILE
if [ $? -ne 0 ]
then
   echo "nginx is not installed ... going to install"
   dnf install nginx -y &>>LOG_FILE
   VALIDATE $? "NGINX"
else
    echo -e "nginx is already installed ... $Y nothing to do $N" &>>LOG_FILE
fi 

dnf list installed python3 &>>LOG_FILE
if [ $? -ne 0 ]
then
   echo "python3 is not installed ... going to install"
   dnf install mysql -y &>>LOG_FILE
   VALIDATE $? "MYSQL"
else
    echo -e "python3 is already installed ... $Y nothing to do $N" &>>LOG_FILE
fi 