#!/bin/bash

USERID=$(id -u)
-gt=greater than
-lt=less than
-eq=equal to
-ne=not equal

if [ $USERID -ne 0 ]
then
   echo "ERROR:: please run this script with root access"
   exit 1 # give other than 0 upto 127
else 
   echo "you are running with root access"
fi

# validate function takes input as exit status what command they tried to install
VALIDATE(){
    if [ $1 -eq 0 ]
    then 
       echo "Installing $2 is ... SUCCESS"
    else
       echo "Installing $2 is ... FAILURE"
       exit 1
}

dnf list installed mysql 
if [ $? -ne 0 ]
then 
   echo "mysql is not installed ... going to install"
   dnf install mysql -y
   VALIDATE $? "mysql"
else
   echo "mysql is already installed ... nothing to do"
fi

dnf list installed nginx
if [ $? -ne 0 ]
then 
   echo "nginx is not installed ... going to install"
   dnf install nginx -y
   VALIDATE $? "NGINX"
else
   echo "nginx is already installed ... nothing to do"
fi

dnf list installed python3
if [ $? -ne 0 ]
then 
   echo "python3 is not installed ... going to install"
   dnf install python3 -y
   VALIDATE $? "PYTHON3"
else 
   echo "python3 is already installed ... nothing to do"
fi
 




