#!/bin/bash
USERID=$(id -u)

R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"
LOGS_FOLDER="/var/log/shellscript-logs"
SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"
PACKAGES=("mysql" "nginx" "httpd")
mkdir -p $LOGS_FOLDER
echo "script started execution at: $(date)" | tee -a $LOG_FILE

if [ $USERID -ne 0 ]
then 
   echo -e "$R ERROR:: please run this script with root access"
   exit 1
else
   echo "you are running with root accesss"
fi

# validate function takes input as exit status what command thay tried to install
VALIDATE(){
    if [ $1 -eq 0 ]
    then
        echo -e "Installing $2 is ... $G SUCCESS $N"
    else
        echo -e "Installing $2 is ... $R FAILURE $N"
        exit 1    
    fi    
}

for package in ${packages [@]}
do 
  dnf list installed $package &>>$LOG_FILE
  if [ $? -ne 0 ]
  then 
     echo -e "package is not installed ... going to installed"
     dnf install $package &>>$LOG_FILE
     VALIDATE $? "$PACKAGE"
  else
     echo -e "nothing to do $package ... $Y already installed $N"
  fi
done     