#!/bin/bash

TO_TEAM=$1
ALERT_TYPE=$2
IP=$3
MSG=$4
FINAL_MSG=$(printf '%s\n' "$MSG" | sed -e 's/[]\/$*.^[]/\\&/g')
TO_ADDRESS=$5
SUBJECT=$6

FINAL_MSG=$(sed -e "s/TO_TEAM/$TO_TEAM/g" -e "s/ALERT_TYPE/$ALERT_TYPE/g" -e "s/IP/$IP/g" -e "s/MSG/$FINAL_MSG/g" -e "s/TO_ADDRESS/$TO_ADDRESS/g" -e "s/SUBJECT/$SUBJECT/g" template.html) 


{
echo "To: $TO_ADDRESS"
echo "Subject: $SUBJECT"
echo "Content-Type: text/html"
echo ""
echo "$FINAL_BODY"
} | msmtp "$TO_ADDRESS"