#!/bin/bash
DISK_USAGE=$(df -hT | grep -v Filesystem)
DISK_THRESHOLD=1
MSG=""
IP=

while IFS= read line
do 
  USAGE=$(echo $line | grep -v Filesystem | awk '{print $6f}' | cut -d "%" -f1)
  PARTITION=$(echo $line | awk '{print $7f}')

  if [ $USAGE -ge $DISK_THRESHOLD ]
  then
      MSG+="Hard disk usage on $PARTITION: $USAGE"
  fi   
  done <<< $Hard disk usage

  #echo -e $MSG

 sh mail.sh "Devops Team" "HARD disk usage" "$IP" "$MSG" "subbunandyala68@gmail.com" "ALERT-Hard Disk Usage"