#!/bin/bash
START_TIME=$(date +%S)
USERID=$(id -u)

LOGS_FOLDER="/var/log/shellscript-logs"
SCRIPT_NAME=$(echo $0 | cut -d "." -f1)
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME.log"
SOURCE_DIR="/home/ec2-user/app-logs"

R="\e[31m"
G="\e[32m"
Y="\e[33m"
N="\e[0m"

mkdir -p $LOGSFOLDER
echo -e "script started execution at: $(date)" | tee -a $LOG_FILE

# check the user have root priveliges or not
if [ $USERID -ne 0 ]
then
    echo -e "$R ERROR:: please run this script with root access $N" | tee -a $LOG_FILE
    exit 1
else 
    echo "you are running with root access" tee -a $LOG_FILE
fi

# validate function takes input as exit status what command that they tried to install
VALIDATE(){
    if [ $1 -eq 0 ]
    then 
        echo -e "Installing $2 is ... $G SUCCESS $N" | tee -a $LOG_FILE
    else 
        echo -e "Installing $2 is ... $R FAILURE $N" | tee -a $LOG_FILE 
        exit 1
    fi        
}

FILES_TO_DELETE=$(find $SOURCE_DIR -name "*.log" -mtime +14)

while IFS= read -r filepath
do 
   echo "Deleting file: $filepath" | tee -a $LOG_FILE
   rm -rf $LOG_FILE
done <<< $FILES_TO_DELETE

echo "script executed successfully"

END_TIME=$(date +%s)
TOTAL_TIME=$(( $END_TIME - $START_TIME )

echo -e "Script execution completed successfully, $Y time taken: $TOTAL_TIME seconds $N" tee -a $LOG_FILE