#!/bin/bash
NUMBER1=100
NUMBER2=200

TIMESTAMP=$(date)
echo "enter your pin number"
read PIN
echo " your number is: $PIN"
echo "script executed at: $TIMESTAMP"

sum=$(( $NUMBER1 and $NUMBER2 ))
echo "sum of $NUMBER1 and $NUMBER2: $SUM"