#!/bin/bash 
NUMBER1=subbu
NUMBER2=200 

echo "enter your pin number"
read -s PIN
echo "your number is: $PIN"

TIMESTAMP=$(date)
echo "script executed at: $TIMESTAMP"
SUM="$(( $NUMBER1 + $NUMBER2 ))"
echo "sum of $number1 and $number2 is: $SUM"