#!/bin/bash
NUMBER1=100
NUMBER2=200

echo "enter your pin number::"
read -s pin
echo "enter your number is: $PIN"

TIMESTAMP=$(date)
echo "script executed at: $TIMESTAMP"
SUM=$(( $NUMBER1 + $NUMBER2 ))
echo "sum of NUMBER1 and NUMBER2 is: $SUM"