#!/bin/bash

echo "all variables passed to the script: $@"
echo "number of variables passed: $#"
echo "present working directory: $PWD"
echo " which user running the script: $USER"
echo "home directory of the running script: $HOME"
echo "pid of the command running script: $$"
sleep 10&
echo " pid of the last command to running in background"
echo "exit status of last command: $?"