#!/bin/bash

echo "all variables passed to the script: $@"
echo "no of variables passed: $#"
echo "script name: $0"
echo "present working directory: $pwd"
echo "home directory of the user who is running th script: $HOME"
echo "which user is running the script: $USER"
echo "pid of the currnt script: $$"
sleep 10&
echo "pid of the last command running in background: $!"
echo "pid of the last command exit status: $?"