#!/bin/bash

USERID=$(id -u)

if [ $USERID -ne 10 ]
then
   echo "given number $NUMBER is less than 10" 
   exit 1 #give other number 0 upto 127
else 
   echo "give number $NUMBER is not less than 10"
fi

# validate function takes input as exit status when they are tried to install it

VALIDATE(){
if [ $1 -eq 0 ]
then
   echo "installing $2 is...SUCCESS"
else
   echo "installing $2 is...FAILURE"
   exit 1
fi          
}

dnf list iinstalled mysql
if [ $? -ne 0 ]
then
   echo "mysql is not installed...going to install"
   dnf install mysql -y
   VALIDATE $? "MYSQL"
else
    echo "mysql is already installed...nothing to do"
fi
dnf list installed python3
if [ $? -eq 0 ] 
then 
    echo "python3 is not installed...going to install"
    dnf install python3
    VALIDATE $? "PYTHON3"
else 
    echo "python3 is already installed...nothing to do"
fi

dnf list installed nginx
if [ $? -eq 0 ]
then
   echo "nginx is not installed...going to install"
else
   echo "nginx is already installedd...nothing to do"
fi
   